service: images-social-server
provider:
  name: aws
  runtime: nodejs16.x
  httpApi:
    cors: true
custom:
  webpack:
    webpackConfig: './webpack.config.js'
functions:
  graphql:
    handler: dist/handler.handler
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
plugins:
  - serverless-offline
  - serverless-webpack