export const DEFAULT_LIMIT = 10;

export const VOTE_COMMENT_ACTION = {
  UPVOTE: 'UPVOTE',
  DOWNVOTE: 'DOWNVOTE',
  CANCEL: 'CANCEL',
};

export const DEFAULT_DEFINED_SKILL_LIST = [
  'Abstract',
  'Animal',
  'Architecture',
  'Artistic',
  'Astrophotography',
  'Attention to Detail',
  'Black and White',
  'Cameras',
  'Cataloging',
  'Celebrities',
  'Cityscape',
  'Color',
  'Color Correcting',
  'Communication',
  'Composition',
  'Concert',
  'Creativity',
  'Cropping',
  'Customer Service',
  'Design',
  'Development',
  'Digital',
  'Digital Imaging',
  'Editing',
  'Editorials',
  'Electronic Image Handling',
  'Entrepreneurial',
  'Equipment',
  'Exposure',
  'Family',
  'Fashion',
  'Film',
  'Fine Art',
  'Flexibility',
  'Food',
  'Form',
  'Formatting',
  'Good Eyesight',
  'HDRI',
  'High Resolution Imaging',
  'Image Manipulation',
  'Imaging',
  'Imaging Technology',
  'Implementing',
  'Industrial',
  'Interior',
  'Interpersonal',
  'Iphoneography',
  'Journalism',
  'Landscape',
  'Lenses',
  'Light Manipulation',
  'Lighting',
  'Locations',
  'Lomo',
  'Macro',
  'Marketing',
  'Media',
  'Nature',
  'Nude',
  'Organization',
  'Patience',
  'Patterns',
  'People',
  'Photo Shoots',
  'Photography Management',
  'Portrait',
  'Preservation',
  'Print',
  'Printing',
  'Problem Solving',
  'Processing',
  'Product',
  'Props',
  'Publicity',
  'Resizing',
  'Retouching',
  'Rural',
  'Sales',
  'Scanning',
  'Sea and Sand',
  'Self-Confidence',
  'Shape',
  'Shooting Film',
  'Simplicity',
  'Slow ISO Speeds',
  'Social',
  'Software',
  'Sports',
  'Still Life',
  'Street Photography',
  'Technical',
  'Technology',
  'Training',
  'Travel',
  'Trying Different Angles',
  'Underwater',
  'Urban',
  'Using Balance',
  'Vehicle',
  'Vintage',
  'Visual',
  'Visual Consistency',
  'Web',
  'Wedding',
  'White Balance',
];

export const googleApplicationCredentials = {
  type: '',
  project_id: '',
  private_key_id: '',
  private_key: '',
  client_email: '',
  client_id: '',
  auth_uri: '',
  token_uri: '',
  auth_provider_x509_cert_url: '',
  client_x509_cert_url: '',
  universe_domain: '',
};
