name: ASP.NET Lambda Deployment

on:
  push:
    branches: [ experiment_deploy ]
  pull_request:
    branches: [ experiment_deploy ]
  workflow_dispatch:

defaults:
  run:
    working-directory: ./Services

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      working-directory: ./Services
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
      AWS_IAM_ROLE_ARN: ${{secrets.AWS_IAM_ROLE_ARN}}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: AWS CLI
      run: dotnet tool install -g Amazon.Lambda.Tools
    - name: Build
      run: dotnet build --no-restore Services.sln
    - name: Deploy to Lambda
      working-directory: ./Services/ApiServices
      run:  dotnet lambda deploy-function --region ${{secrets.AWS_DEFAULT_REGION}} --function-runtime dotnet6 --function-name mythic-empire-backend-service --function-role ${{secrets.AWS_IAM_ROLE_ARN}} 